# Generated by Django 5.0.3 on 2024-03-22 23:31

import django.db.models.deletion
import workout.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefinedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('muscle_group', models.CharField(choices=[('C', 'Chest'), ('B', 'Back'), ('S', 'Shoulders'), ('A', 'Arms'), ('L', 'Legs'), ('Co', 'Core')], max_length=2)),
            ],
            bases=(models.Model, workout.models.MuscleGroup),
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('FB', 'Full Body'), ('UB', 'Upper Body'), ('LB', 'Lower Body'), ('Ph', 'Push'), ('Pl', 'Pull'), ('Ca', 'Cardio'), ('Re', 'Rest Day'), ('C', 'Chest'), ('B', 'Back'), ('S', 'Shoulders'), ('A', 'Arms'), ('L', 'Legs'), ('Co', 'Core')], max_length=2)),
                ('duration', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            bases=(models.Model, workout.models.MuscleGroup),
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('defined_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.definedexercise')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workout.routine')),
            ],
        ),
    ]
